### ISSUE TITLE
Penetration stuck at 3%

### ISSUE THREAD

**Issue by EmilienCourt** [NORMA-Company/Atear-Beta#13]
Hi,

I'm getting an error while launching the Penetration option (while the interface os is stuck at 3%)
Here is the error from the terminal :

> [2016-11-07 23:25:07,381] ERROR in app: Exception on /api/pentest [POST]
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "run.py", line 212, in pentest
>     self.wids_handle.terminate()
> AttributeError: 'bool' object has no attribute 'terminate'
> 127.0.0.1 - - [07/Nov/2016 23:25:07] "POST /api/pentest HTTP/1.1" 500 -
> 127.0.0.1 - - [07/Nov/2016 23:25:07] "GET /api/hidden/0 HTTP/1.1" 200 -
> [2016-11-07 23:25:12,474] ERROR in app: Exception on /api/pentest [GET]
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "run.py", line 212, in pentest
>     self.wids_handle.terminate()
> AttributeError: 'bool' object has no attribute 'terminate'
> 127.0.0.1 - - [07/Nov/2016 23:25:12] "GET /api/pentest HTTP/1.1" 500 -

And here is the [log folder](https://github.com/NORMA-Inc/AtEar/files/576804/log.zip)
Thanks

**Comment by Indeserpen** [comment]
Can confirm it:
raceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run.py", line 212, in pentest
    self.wids_handle.terminate()
AttributeError: 'bool' object has no attribute 'terminate'
127.0.0.1 - - [01/Dec/2016 15:13:07] "POST /api/pentest HTTP/1.1" 500 -
[2016-12-01 15:13:12,947] ERROR in app: Exception on /api/pentest [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run.py", line 212, in pentest
    self.wids_handle.terminate()
AttributeError: 'bool' object has no attribute 'terminate'
127.0.0.1 - - [01/Dec/2016 15:13:12] "GET /api/pentest HTTP/1.1" 500 -
^C
![screenshot from 2016-12-01 15-13-24](https://cloud.githubusercontent.com/assets/13330266/20816793/b27c73f4-b82c-11e6-893c-e03962b8423f.png)

What flask version it depends?

**Comment by Indeserpen** [comment]
So i updated all my python-files and have no issues with python-flask but I,m stil stuck on 3 %

[*] Start scanning network 
[*] START AtEar-WIDS
/root/AtEar
[*] START AtEar-UI
127.0.0.1 - - [03/Dec/2016 15:10:33] "GET /api/scanstatus HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:10:34] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:10:39] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:10:43] "GET /api/scanstatus HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:10:44] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:10:49] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:10:54] "GET /api/scanstatus HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:10:54] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:00] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:06] "GET /api/scanstatus HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:06] "GET /api/hidden/0 HTTP/1.1" 200 -
[*] Stop Scanning networkp
127.0.0.1 - - [03/Dec/2016 15:11:08] "POST /api/scanstatus HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:12] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:17] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:22] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:27] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:32] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:37] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:42] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:47] "POST /api/pentest HTTP/1.1" 500 -
127.0.0.1 - - [03/Dec/2016 15:11:47] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:52] "GET /api/pentest HTTP/1.1" 500 -
127.0.0.1 - - [03/Dec/2016 15:11:52] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:11:57] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:02] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:07] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:12] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:17] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:22] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:27] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:32] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:37] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:42] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:47] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:52] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:12:57] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:13:02] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:13:07] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:13:12] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2016 15:

**Comment by DizKiller** [comment]
I have been getting the same error. stuck at 3% and this:


[2017-12-14 01:44:11,304] ERROR in app: Exception on /api/pentest [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run.py", line 212, in pentest
    self.wids_handle.terminate()
AttributeError: 'bool' object has no attribute 'terminate'
127.0.0.1 - - [14/Dec/2017 01:44:11] "POST /api/pentest HTTP/1.1" 500 -
127.0.0.1 - - [14/Dec/2017 01:44:14] "GET /api/hidden/0 HTTP/1.1" 200 -
[2017-12-14 01:44:16,342] ERROR in app: Exception on /api/pentest [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run.py", line 212, in pentest
    self.wids_handle.terminate()
AttributeError: 'bool' object has no attribute 'terminate'

127.0.0.1 - - [14/Dec/2017 01:44:16] "GET /api/pentest HTTP/1.1" 500 -
127.0.0.1 - - [14/Dec/2017 01:23:04] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:09] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:14] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:19] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:24] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:29] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:34] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:39] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:44] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:49] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:54] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:23:59] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:04] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:09] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:14] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:19] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:24] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:29] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:34] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:39] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:44] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:49] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:54] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:24:59] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:04] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:09] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:14] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:19] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:24] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:29] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:34] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:39] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:44] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:49] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:54] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:25:59] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:04] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:09] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:14] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:19] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:24] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:29] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:34] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:39] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:44] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:49] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:54] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:26:59] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:04] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:09] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:14] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:19] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:24] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:29] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:34] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:39] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:44] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:49] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:54] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:27:59] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:28:04] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:28:09] "GET /api/hidden/0 HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 01:28:14] "GET /api/hidden/0 HTTP/1.1" 200 -

**Comment by anhb** [comment]
I have same error, installed all dependencies on archlinux but doesn't work
