### ISSUE TITLE
WIDS: ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by noraj** [NORMA-Company/Atear-Beta#19]
Just clicking the WIDS menu generates an error:

```
[2019-01-25 19:07:13,852] ERROR in app: Exception on /api/wids [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run.py", line 194, in wids
    self.wids_handle = Wireless_IDS('atear_wids')
  File "/usr/share/atear/module/wids.py", line 90, in __init__
    signal.signal(signal.SIGTERM, signal_handler)
ValueError: signal only works in main thread
```

And of course nothing appear.

**Comment by Punyah** [comment]
If you have not solved the problem.
That is the solution.
Need flask version 0.10.1.
Command: pip install Flask==0.10.1
