### ISSUE TITLE
 ERROR in app: Exception on /api/scanstatus [GET]

### ISSUE THREAD

**Issue by jepunband** [NORMA-Company/Atear-Beta#21]
[*] START AtEar-WIDS
/home/trex/projects/AtEar
[2020-11-21 15:37:20,873] ERROR in app: Exception on /api/scanstatus [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run.py", line 100, in scanstatus
    wids = Wireless_IDS(self.scan_iface)
  File "/home/trex/projects/AtEar/module/wids.py", line 90, in __init__
    signal.signal(signal.SIGTERM, signal_handler)
ValueError: signal only works in main thread
127.0.0.1 - - [21/Nov/2020 15:37:20] "GET /api/scanstatus HTTP/1.1" 500 -

**Comment by l4rm4nd** [comment]
The GitHub project is kinda old now. The code has been released 6 years ago.

The `requirements.txt` also just lists pip packages, but without any compatible versions. Therefore, if you nowadays just execute `pip install -r requirements`, you will install the newest pip packages. The newest `flask` package is not compatible anymore and will throw the signal error message.

An easy fix is to just downgrade flask to an older package version. I've used flask==0.11 from May 29, 2016, which seems to work.

**Installation instructions**
````
cd /opt/
git clone https://github.com/NORMA-Inc/AtEar
cd AtEar 
virtualnenv -p python2.7 venv # create a virtual env for deprecated python2.7
source venv/bin/activate # activate the virtual env
python install -r requirements.txt # install recommended requirements
pip uninstall flask # remove flask, since it is too new and not compatible with AtEar
pip install flask==0.11 # install compatible flask v0.11 from 2016

# run the script
python run.py --iface <interface>
````
I have a [forked repo](https://github.com/l4rm4nd/AtEar) with updated information.

**Comment by zararashigal** [comment]
Dead project. Move along. :(
